### ISSUE TITLE
scrfd_10g_bnkps detection model cannot detect lower resolution images such as 300*300 unless given lower threshold such as 0.2 or 0.3

### ISSUE THREAD

**Issue by Asher-1** [SthPhoenix/InsightFace-REST#41]
MAX_SIZE="640,640"
DET_THRESH=0.6 --> no faces detected
DET_THRESH=0.5 --> no faces detected
DET_THRESH=0.4 --> no faces detected
DET_THRESH=0.3 --> find faces

**Comment by SthPhoenix** [comment]
Unfortunately this is issue related to scrfd bnkps models: deepinsight/insightface#1518

I'm currently retraining various versions of scrfd models which fixes this issue.

**Comment by SthPhoenix** [comment]
I have released retrained SCRFD models, could you please check if they solves your issue?

**Comment by Asher-1** [comment]
Thanks for your work!
I have tested scrfd_10g_gnkps model and it works for me, but still have the same issue on scrfd_10g_bnkps

**Comment by SthPhoenix** [comment]
> Thanks for your work!
> I have tested scrfd_10g_gnkps model and it works for me, but still have the same issue on scrfd_10g_bnkps

Unfortunately this issue can't be fixed for original models, it can be worked around by second detection step at lower resolution, but it will cause additional computational costs for images without faces and unnecessary code complexity.

**Comment by SthPhoenix** [comment]
Closing as resolved with updated model.
